package com.hbm.registry;

import java.util.function.Consumer;
import java.util.function.Supplier;

import com.hbm.HbmNuclearTech;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public final class HbmCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
        DeferredRegister.create(Registries.CREATIVE_MODE_TAB, HbmNuclearTech.MODID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> PARTS = registerTab(
        "parts",
        "itemGroup.tabParts",
        () -> new ItemStack(HbmItems.INGOT_URANIUM.get()),
        HbmItems::addDynamicPartsTabItems,
        HbmItems.INGOT_STEEL,
        HbmItems.INGOT_COPPER,
        HbmItems.INGOT_RED_COPPER,
        HbmItems.INGOT_TITANIUM,
        HbmItems.INGOT_TUNGSTEN,
        HbmItems.INGOT_ALUMINIUM,
        HbmItems.INGOT_BERYLLIUM,
        HbmItems.INGOT_LEAD,
        HbmItems.INGOT_ADVANCED_ALLOY,
        HbmItems.INGOT_URANIUM,
        HbmItems.HAZMAT_CLOTH,
        HbmItems.CRYSTAL_IRON,
        HbmItems.CRYSTAL_GOLD,
        HbmItems.CRYSTAL_REDSTONE,
        HbmItems.CRYSTAL_LAPIS,
        HbmItems.CRYSTAL_DIAMOND,
        HbmItems.CRYSTAL_URANIUM,
        HbmItems.CRYSTAL_THORIUM,
        HbmItems.CRYSTAL_PLUTONIUM,
        HbmItems.CRYSTAL_TITANIUM,
        HbmItems.CRYSTAL_SULFUR,
        HbmItems.CRYSTAL_NITER,
        HbmItems.CRYSTAL_COPPER,
        HbmItems.CRYSTAL_TUNGSTEN,
        HbmItems.CRYSTAL_ALUMINIUM,
        HbmItems.CRYSTAL_FLUORITE,
        HbmItems.CRYSTAL_BERYLLIUM,
        HbmItems.CRYSTAL_LEAD,
        HbmItems.CRYSTAL_ASBESTOS,
        HbmItems.CRYSTAL_RARE,
        HbmItems.CRYSTAL_PHOSPHORUS,
        HbmItems.CRYSTAL_LITHIUM,
        HbmItems.CRYSTAL_CINNEBAR,
        HbmItems.CRYSTAL_COBALT,
        HbmItems.CRYSTAL_STARMETAL,
        HbmItems.GEM_TANTALIUM,
        HbmItems.PLATE_COPPER,
        HbmItems.PLATE_ALUMINIUM,
        HbmItems.PLATE_IRON,
        HbmItems.PLATE_GOLD,
        HbmItems.PLATE_LEAD,
        HbmItems.PLATE_STEEL,
        HbmItems.PLATE_ADVANCED_ALLOY,
        HbmItems.PLATE_TITANIUM,
        HbmItems.PLATE_COMBINE_STEEL,
        HbmItems.PLATE_SATURNITE,
        HbmItems.PLATE_DALEKANIUM,
        HbmItems.PLATE_MIXED,
        HbmItems.PLATE_ARMOR_TITANIUM,
        HbmItems.PLATE_ARMOR_AJR,
        HbmItems.PLATE_ARMOR_HEV,
        HbmItems.PLATE_ARMOR_LUNAR,
        HbmItems.PLATE_ARMOR_FAU,
        HbmItems.PLATE_ARMOR_DNT,
        HbmItems.COIL_COPPER,
        HbmItems.COIL_COPPER_TORUS,
        HbmItems.COIL_ADVANCED_ALLOY,
        HbmItems.COIL_ADVANCED_TORUS,
        HbmItems.COIL_GOLD,
        HbmItems.COIL_GOLD_TORUS,
        HbmItems.COIL_TUNGSTEN,
        HbmItems.COIL_MAGNETIZED_TUNGSTEN,
        HbmItems.UPGRADE_TEMPLATE,
        HbmItems.DEUTERIUM_FILTER,
        HbmItems.CIRCUIT_VACUUM_TUBE,
        HbmItems.CIRCUIT_CAPACITOR,
        HbmItems.CIRCUIT_CAPACITOR_TANTALIUM,
        HbmItems.CIRCUIT_ATOMIC_CLOCK,
        HbmItems.CIRCUIT_PCB,
        HbmItems.CIRCUIT_CRT_TUBE,
        HbmItems.CIRCUIT_SILICON,
        HbmItems.CIRCUIT_CHIP,
        HbmItems.CIRCUIT_CHIP_BISMOID,
        HbmItems.CIRCUIT_CHIP_QUANTUM,
        HbmItems.CIRCUIT_ANALOG,
        HbmItems.CIRCUIT_BASIC,
        HbmItems.CIRCUIT_CAPACITOR_BOARD,
        HbmItems.CIRCUIT_ADVANCED,
        HbmItems.CIRCUIT_BISMOID,
        HbmItems.CIRCUIT_QUANTUM,
        HbmItems.CIRCUIT_CONTROLLER_CHASSIS,
        HbmItems.CIRCUIT_CONTROLLER,
        HbmItems.CIRCUIT_CONTROLLER_ADVANCED,
        HbmItems.CIRCUIT_CONTROLLER_QUANTUM,
        HbmItems.MECHANISM_REVOLVER_1,
        HbmItems.MECHANISM_REVOLVER_2,
        HbmItems.MECHANISM_RIFLE_1,
        HbmItems.MECHANISM_RIFLE_2,
        HbmItems.MECHANISM_LAUNCHER_1,
        HbmItems.MECHANISM_LAUNCHER_2,
        HbmItems.MECHANISM_SPECIAL,
        HbmItems.PRIMER_357,
        HbmItems.PRIMER_44,
        HbmItems.PRIMER_9,
        HbmItems.PRIMER_50,
        HbmItems.PRIMER_BUCKSHOT,
        HbmItems.CASING_357,
        HbmItems.CASING_44,
        HbmItems.CASING_9,
        HbmItems.CASING_50,
        HbmItems.CASING_BUCKSHOT,
        HbmItems.ASSEMBLY_IRON,
        HbmItems.ASSEMBLY_STEEL,
        HbmItems.ASSEMBLY_LEAD,
        HbmItems.ASSEMBLY_GOLD,
        HbmItems.ASSEMBLY_SCHRABIDIUM,
        HbmItems.ASSEMBLY_NIGHTMARE,
        HbmItems.ASSEMBLY_DESH,
        HbmItems.ASSEMBLY_NOPIP,
        HbmItems.ASSEMBLY_SMG,
        HbmItems.ASSEMBLY_556,
        HbmItems.ASSEMBLY_UZI,
        HbmItems.ASSEMBLY_ACTIONEXPRESS,
        HbmItems.ASSEMBLY_CALAMITY,
        HbmItems.ASSEMBLY_LACUNAE,
        HbmItems.ASSEMBLY_NUKE
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CONTROL = registerTab(
        "control",
        "itemGroup.tabControl",
        () -> new ItemStack(Items.REDSTONE),
        (Consumer<CreativeModeTab.Output>) HbmItems::addDynamicControlTabItems,
        sup(Items.REDSTONE),
        sup(Items.REPEATER),
        sup(Items.BLAZE_POWDER),
        HbmItems.MOLD_BASE
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> TEMPLATE = registerTab(
        "template",
        "itemGroup.tabTemplate",
        () -> new ItemStack(Items.PAPER),
        sup(Items.PAPER),
        sup(Items.BOOK),
        sup(Items.WRITABLE_BOOK)
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> RESOURCE = registerTab(
        "resource",
        "itemGroup.tabResource",
        () -> new ItemStack(HbmBlocks.ORE_TITANIUM.get()),
        HbmBlocks.STONE_GNEISS,
        HbmBlocks.STONE_CRACKED,
        HbmBlocks.BASALT,
        HbmBlocks.BASALT_SMOOTH,
        HbmBlocks.BASALT_BRICK,
        HbmBlocks.BASALT_POLISHED,
        HbmBlocks.BASALT_TILES,
        HbmBlocks.ORE_ALUMINIUM,
        HbmBlocks.ORE_BERYLLIUM,
        HbmBlocks.ORE_CINNEBAR,
        HbmBlocks.ORE_COBALT,
        HbmBlocks.ORE_COPPER,
        HbmBlocks.ORE_FLUORITE,
        HbmBlocks.ORE_LEAD,
        HbmBlocks.ORE_NITER,
        HbmBlocks.ORE_SULFUR,
        HbmBlocks.ORE_TITANIUM,
        HbmBlocks.ORE_TUNGSTEN,
        HbmBlocks.BLOCK_BISMUTH,
        HbmBlocks.BLOCK_BORON,
        HbmBlocks.BLOCK_CADMIUM,
        HbmBlocks.BLOCK_COBALT,
        HbmBlocks.BLOCK_COMBINE_STEEL,
        HbmBlocks.BLOCK_COPPER,
        HbmBlocks.BLOCK_DESH,
        HbmBlocks.BLOCK_DINEUTRONIUM,
        HbmBlocks.BLOCK_DURA_STEEL,
        HbmBlocks.BLOCK_EUPHEMIUM,
        HbmBlocks.BLOCK_FLUORITE,
        HbmBlocks.BLOCK_LANTHANIUM,
        HbmBlocks.BLOCK_NIOBIUM,
        HbmBlocks.BLOCK_RED_COPPER,
        HbmBlocks.BLOCK_SATURNITE,
        HbmBlocks.BLOCK_STARMETAL,
        HbmBlocks.BLOCK_STEEL,
        HbmBlocks.BLOCK_TANTALIUM,
        HbmBlocks.BLOCK_TITANIUM,
        HbmBlocks.BLOCK_TUNGSTEN,
        HbmBlocks.BLOCK_ZIRCONIUM,
        HbmBlocks.BLOCK_ACTINIUM,
        HbmBlocks.BLOCK_AUSTRALIUM,
        HbmBlocks.BLOCK_BAKELITE,
        HbmBlocks.BLOCK_DAFFERGON,
        HbmBlocks.BLOCK_POLYMER,
        HbmBlocks.BLOCK_REIIUM,
        HbmBlocks.BLOCK_RUBBER,
        HbmBlocks.BLOCK_UNOBTAINIUM,
        HbmBlocks.BLOCK_VERTICIUM,
        HbmBlocks.BLOCK_WEIDANIUM,
        HbmBlocks.BLOCK_ALUMINIUM,
        HbmBlocks.BLOCK_BERYLLIUM,
        HbmBlocks.BLOCK_LEAD,
        HbmBlocks.BLOCK_ADVANCED_ALLOY,
        HbmBlocks.ORE_BEDROCK_OIL,
        HbmBlocks.ORE_OIL_EMPTY,
        HbmBlocks.TEKTITE,
        HbmBlocks.ORE_TEKTITE_OSMIRIDIUM
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> BLOCKS = registerTab(
        "blocks",
        "itemGroup.tabBlocks",
        () -> new ItemStack(HbmBlocks.CONCRETE_HAZARD.get()),
        HbmBlocks.ASPHALT,
        HbmBlocks.BLOCK_SLAG,
        HbmBlocks.METEOR_POLISHED,
        HbmBlocks.METEOR_BRICK,
        HbmBlocks.METEOR_BRICK_MOSSY,
        HbmBlocks.METEOR_BRICK_CRACKED,
        HbmBlocks.METEOR_BRICK_CHISELED,
        HbmBlocks.BRICK_DUNGEON,
        HbmBlocks.BRICK_DUNGEON_FLAT,
        HbmBlocks.BRICK_DUNGEON_TILE,
        HbmBlocks.BRICK_DUNGEON_CIRCLE,
        HbmBlocks.MUFFLER,
        HbmBlocks.REINFORCED_GLASS,
        HbmBlocks.REINFORCED_STONE,
        HbmBlocks.REINFORCED_STONE_STAIRS,
        HbmBlocks.REINFORCED_STONE_SLAB,
        HbmBlocks.BRICK_CONCRETE,
        HbmBlocks.BRICK_CONCRETE_STAIRS,
        HbmBlocks.BRICK_CONCRETE_SLAB,
        HbmBlocks.BRICK_CONCRETE_MOSSY,
        HbmBlocks.BRICK_CONCRETE_MOSSY_STAIRS,
        HbmBlocks.BRICK_CONCRETE_MOSSY_SLAB,
        HbmBlocks.BRICK_CONCRETE_CRACKED,
        HbmBlocks.BRICK_CONCRETE_CRACKED_STAIRS,
        HbmBlocks.BRICK_CONCRETE_CRACKED_SLAB,
        HbmBlocks.BRICK_CONCRETE_BROKEN,
        HbmBlocks.BRICK_CONCRETE_BROKEN_STAIRS,
        HbmBlocks.BRICK_CONCRETE_BROKEN_SLAB,
        HbmBlocks.REINFORCED_BRICK,
        HbmBlocks.REINFORCED_BRICK_STAIRS,
        HbmBlocks.REINFORCED_BRICK_SLAB,
        HbmBlocks.BRICK_COMPOUND,
        HbmBlocks.BRICK_COMPOUND_STAIRS,
        HbmBlocks.BRICK_COMPOUND_SLAB,
        HbmBlocks.BRICK_FIRE,
        HbmBlocks.BRICK_FIRE_STAIRS,
        HbmBlocks.BRICK_FIRE_SLAB,
        HbmBlocks.BRICK_LIGHT,
        HbmBlocks.BRICK_LIGHT_STAIRS,
        HbmBlocks.BRICK_LIGHT_SLAB,
        HbmBlocks.REINFORCED_SAND,
        HbmBlocks.REINFORCED_SAND_STAIRS,
        HbmBlocks.REINFORCED_SAND_SLAB,
        HbmBlocks.BRICK_OBSIDIAN,
        HbmBlocks.BRICK_OBSIDIAN_STAIRS,
        HbmBlocks.BRICK_OBSIDIAN_SLAB,
        HbmBlocks.CMB_BRICK,
        HbmBlocks.CMB_BRICK_REINFORCED,
        HbmBlocks.CMB_BRICK_REINFORCED_STAIRS,
        HbmBlocks.CMB_BRICK_REINFORCED_SLAB,
        HbmBlocks.DUCRETE_SMOOTH,
        HbmBlocks.DUCRETE_SMOOTH_STAIRS,
        HbmBlocks.DUCRETE_SMOOTH_SLAB,
        HbmBlocks.DUCRETE,
        HbmBlocks.DUCRETE_STAIRS,
        HbmBlocks.DUCRETE_SLAB,
        HbmBlocks.DUCRETE_BRICK,
        HbmBlocks.DUCRETE_BRICK_STAIRS,
        HbmBlocks.DUCRETE_BRICK_SLAB,
        HbmBlocks.DUCRETE_REINFORCED,
        HbmBlocks.DUCRETE_REINFORCED_STAIRS,
        HbmBlocks.DUCRETE_REINFORCED_SLAB,
        HbmBlocks.TILE_LAB,
        HbmBlocks.TILE_LAB_STAIRS,
        HbmBlocks.TILE_LAB_SLAB,
        HbmBlocks.TILE_LAB_CRACKED,
        HbmBlocks.TILE_LAB_CRACKED_STAIRS,
        HbmBlocks.TILE_LAB_CRACKED_SLAB,
        HbmBlocks.TILE_LAB_BROKEN,
        HbmBlocks.TILE_LAB_BROKEN_STAIRS,
        HbmBlocks.TILE_LAB_BROKEN_SLAB,
        HbmBlocks.CONCRETE,
        HbmBlocks.CONCRETE_STAIRS,
        HbmBlocks.CONCRETE_SLAB,
        HbmBlocks.CONCRETE_SMOOTH,
        HbmBlocks.CONCRETE_SMOOTH_STAIRS,
        HbmBlocks.CONCRETE_SMOOTH_SLAB,
        HbmBlocks.CONCRETE_WHITE,
        HbmBlocks.CONCRETE_WHITE_STAIRS,
        HbmBlocks.CONCRETE_WHITE_SLAB,
        HbmBlocks.CONCRETE_ORANGE,
        HbmBlocks.CONCRETE_ORANGE_STAIRS,
        HbmBlocks.CONCRETE_ORANGE_SLAB,
        HbmBlocks.CONCRETE_MAGENTA,
        HbmBlocks.CONCRETE_MAGENTA_STAIRS,
        HbmBlocks.CONCRETE_MAGENTA_SLAB,
        HbmBlocks.CONCRETE_LIGHT_BLUE,
        HbmBlocks.CONCRETE_LIGHT_BLUE_STAIRS,
        HbmBlocks.CONCRETE_LIGHT_BLUE_SLAB,
        HbmBlocks.CONCRETE_YELLOW,
        HbmBlocks.CONCRETE_YELLOW_STAIRS,
        HbmBlocks.CONCRETE_YELLOW_SLAB,
        HbmBlocks.CONCRETE_LIME,
        HbmBlocks.CONCRETE_LIME_STAIRS,
        HbmBlocks.CONCRETE_LIME_SLAB,
        HbmBlocks.CONCRETE_PINK,
        HbmBlocks.CONCRETE_PINK_STAIRS,
        HbmBlocks.CONCRETE_PINK_SLAB,
        HbmBlocks.CONCRETE_GRAY,
        HbmBlocks.CONCRETE_GRAY_STAIRS,
        HbmBlocks.CONCRETE_GRAY_SLAB,
        HbmBlocks.CONCRETE_SILVER,
        HbmBlocks.CONCRETE_SILVER_STAIRS,
        HbmBlocks.CONCRETE_SILVER_SLAB,
        HbmBlocks.CONCRETE_CYAN,
        HbmBlocks.CONCRETE_CYAN_STAIRS,
        HbmBlocks.CONCRETE_CYAN_SLAB,
        HbmBlocks.CONCRETE_PURPLE,
        HbmBlocks.CONCRETE_PURPLE_STAIRS,
        HbmBlocks.CONCRETE_PURPLE_SLAB,
        HbmBlocks.CONCRETE_BLUE,
        HbmBlocks.CONCRETE_BLUE_STAIRS,
        HbmBlocks.CONCRETE_BLUE_SLAB,
        HbmBlocks.CONCRETE_BROWN,
        HbmBlocks.CONCRETE_BROWN_STAIRS,
        HbmBlocks.CONCRETE_BROWN_SLAB,
        HbmBlocks.CONCRETE_GREEN,
        HbmBlocks.CONCRETE_GREEN_STAIRS,
        HbmBlocks.CONCRETE_GREEN_SLAB,
        HbmBlocks.CONCRETE_RED,
        HbmBlocks.CONCRETE_RED_STAIRS,
        HbmBlocks.CONCRETE_RED_SLAB,
        HbmBlocks.CONCRETE_BLACK,
        HbmBlocks.CONCRETE_BLACK_STAIRS,
        HbmBlocks.CONCRETE_BLACK_SLAB,
        HbmBlocks.CONCRETE_HAZARD,
        HbmBlocks.CRATE_IRON,
        HbmBlocks.CRATE_STEEL,
        HbmBlocks.CRATE_DESH,
        HbmBlocks.SAFE,
        HbmBlocks.MACHINE_PRESS,
        HbmBlocks.MACHINE_EPRESS,
        HbmBlocks.MACHINE_ELECTRIC_FURNACE,
        HbmBlocks.MACHINE_TRANSFORMER,
        HbmBlocks.MACHINE_TRANSFORMER_20,
        HbmBlocks.MACHINE_TRANSFORMER_DNT,
        HbmBlocks.MACHINE_TRANSFORMER_DNT_20,
        HbmBlocks.MACHINE_BATTERY_POTATO,
        HbmBlocks.MACHINE_BATTERY,
        HbmBlocks.MACHINE_LITHIUM_BATTERY,
        HbmBlocks.MACHINE_DESH_BATTERY,
        HbmBlocks.MACHINE_SATURNITE_BATTERY,
        HbmBlocks.MACHINE_SCHRABIDIUM_BATTERY,
        HbmBlocks.MACHINE_EUPHEMIUM_BATTERY,
        HbmBlocks.MACHINE_RADSPICE_BATTERY,
        HbmBlocks.MACHINE_DINEUTRONIUM_BATTERY,
        HbmBlocks.MACHINE_ELECTRONIUM_BATTERY,
        HbmBlocks.RED_CABLE,
        HbmBlocks.CABLE_SWITCH,
        HbmBlocks.CABLE_DETECTOR,
        HbmBlocks.CABLE_DIODE,
        HbmBlocks.RED_CABLE_GAUGE,
        HbmBlocks.RED_CONNECTOR,
        HbmBlocks.FLUID_DUCT_MK2,
        HbmBlocks.FLUID_DUCT_SOLID,
        HbmBlocks.FLUID_DUCT_SOLID_SEALED,
        HbmBlocks.MACHINE_SHREDDER,
        HbmBlocks.PRESS_PREHEATER,
        HbmBlocks.METEOR_BATTERY,
        HbmBlocks.BRICK_JUNGLE,
        HbmBlocks.BRICK_JUNGLE_CRACKED,
        HbmBlocks.BLOCK_NITER,
        HbmBlocks.BLOCK_SULFUR,
        HbmBlocks.DECO_TITANIUM,
        HbmBlocks.DECO_RED_COPPER,
        HbmBlocks.DECO_TUNGSTEN,
        HbmBlocks.DECO_ALUMINIUM,
        HbmBlocks.DECO_STEEL,
        HbmBlocks.DECO_LEAD,
        HbmBlocks.DECO_BERYLLIUM,
        HbmBlocks.BLOCK_SMORE,
        HbmBlocks.BLOCK_FOAM,
        HbmBlocks.BLOCK_CAP_NUKA,
        HbmBlocks.BLOCK_CAP_QUANTUM,
        HbmBlocks.BLOCK_CAP_RAD,
        HbmBlocks.BLOCK_CAP_SPARKLE,
        HbmBlocks.BLOCK_CAP_KORL,
        HbmBlocks.BLOCK_CAP_FRITZ,
        HbmBlocks.BLOCK_CAP_SUNSET,
        HbmBlocks.BLOCK_CAP_STAR
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MACHINE = registerTab(
        "machine",
        "itemGroup.tabMachine",
        () -> new ItemStack(HbmBlocks.MACHINE_PRESS.get()),
        HbmBlocks.MACHINE_PRESS,
        HbmBlocks.MACHINE_EPRESS,
        HbmBlocks.MACHINE_ELECTRIC_FURNACE,
        HbmBlocks.MACHINE_TRANSFORMER,
        HbmBlocks.MACHINE_TRANSFORMER_20,
        HbmBlocks.MACHINE_TRANSFORMER_DNT,
        HbmBlocks.MACHINE_TRANSFORMER_DNT_20,
        HbmBlocks.MACHINE_BATTERY_POTATO,
        HbmBlocks.MACHINE_BATTERY,
        HbmBlocks.MACHINE_LITHIUM_BATTERY,
        HbmBlocks.MACHINE_DESH_BATTERY,
        HbmBlocks.MACHINE_SATURNITE_BATTERY,
        HbmBlocks.MACHINE_SCHRABIDIUM_BATTERY,
        HbmBlocks.MACHINE_EUPHEMIUM_BATTERY,
        HbmBlocks.MACHINE_RADSPICE_BATTERY,
        HbmBlocks.MACHINE_DINEUTRONIUM_BATTERY,
        HbmBlocks.MACHINE_ELECTRONIUM_BATTERY,
        HbmBlocks.RED_CABLE,
        HbmBlocks.CABLE_SWITCH,
        HbmBlocks.CABLE_DETECTOR,
        HbmBlocks.CABLE_DIODE,
        HbmBlocks.RED_CABLE_GAUGE,
        HbmBlocks.RED_CONNECTOR,
        HbmBlocks.FLUID_DUCT_MK2,
        HbmBlocks.FLUID_DUCT_SOLID,
        HbmBlocks.FLUID_DUCT_SOLID_SEALED,
        HbmBlocks.MACHINE_SHREDDER,
        HbmBlocks.BARREL_PLASTIC,
        HbmBlocks.BARREL_CORRODED,
        HbmBlocks.BARREL_IRON,
        HbmBlocks.BARREL_STEEL,
        HbmBlocks.BARREL_TCALLOY,
        HbmBlocks.BARREL_ANTIMATTER,
        HbmBlocks.PRESS_PREHEATER,
        HbmBlocks.SEAL_FRAME,
        HbmBlocks.FACTORY_TITANIUM_HULL,
        HbmBlocks.FACTORY_ADVANCED_HULL,
        HbmBlocks.FUSION_HATCH,
        HbmBlocks.FUSION_CORE_BLOCK,
        HbmBlocks.WATZ_ELEMENT,
        HbmBlocks.WATZ_COOLER,
        HbmBlocks.FWATZ_SCAFFOLD,
        HbmBlocks.FWATZ_COMPUTER,
        sup(Items.PISTON),
        sup(Items.HOPPER),
        sup(Items.BLAST_FURNACE)
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> NUKE = registerTab(
        "nuke",
        "itemGroup.tabNuke",
        () -> new ItemStack(Items.TNT),
        (Consumer<CreativeModeTab.Output>) HbmItems::addDynamicNukeTabItems,
        sup(Items.TNT),
        sup(Items.FIRE_CHARGE),
        sup(Items.END_CRYSTAL)
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MISSILE = registerTab(
        "missile",
        "itemGroup.tabMissile",
        () -> new ItemStack(HbmItems.MISSILE_NUCLEAR.get()),
        HbmItems.MISSILE_NUCLEAR,
        HbmBlocks.STRUCT_LAUNCHER,
        HbmBlocks.STRUCT_SCAFFOLD,
        sup(Items.FIREWORK_ROCKET),
        sup(Items.SPECTRAL_ARROW)
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> WEAPON = registerTab(
        "weapon",
        "itemGroup.tabWeapon",
        () -> new ItemStack(Items.CROSSBOW),
        (Consumer<CreativeModeTab.Output>) HbmItems::addDynamicWeaponTabItems,
        sup(Items.CROSSBOW),
        sup(Items.IRON_SWORD),
        sup(Items.SHIELD),
        HbmItems.GRENADE_GENERIC,
        HbmItems.ENTITY_GLOWING_ONE_SPAWN_EGG,
        HbmItems.ENTITY_NUCLEAR_CREEPER_SPAWN_EGG,
        HbmItems.ENTITY_TAINTED_CREEPER_SPAWN_EGG
    );

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CONSUMABLE = registerTab(
        "consumable",
        "itemGroup.tabConsumable",
        () -> new ItemStack(HbmItems.RADAWAY.get()),
        (Consumer<CreativeModeTab.Output>) HbmItems::addDynamicConsumableTabItems,
        sup(Items.GOLDEN_CARROT),
        sup(Items.COOKED_BEEF),
        sup(Items.POTION)
    );

    private HbmCreativeTabs() {
    }

    @SafeVarargs
    private static DeferredHolder<CreativeModeTab, CreativeModeTab> registerTab(
        String id,
        String translationKey,
        Supplier<ItemStack> icon,
        Supplier<? extends ItemLike>... displayItems
    ) {
        return registerTab(id, translationKey, icon, null, displayItems);
    }

    @SafeVarargs
    private static DeferredHolder<CreativeModeTab, CreativeModeTab> registerTab(
        String id,
        String translationKey,
        Supplier<ItemStack> icon,
        Consumer<CreativeModeTab.Output> dynamicItems,
        Supplier<? extends ItemLike>... displayItems
    ) {
        return CREATIVE_MODE_TABS.register(id, () -> CreativeModeTab.builder()
            .title(Component.translatable(translationKey))
            .icon(icon)
            .displayItems((parameters, output) -> {
                for (Supplier<? extends ItemLike> itemSupplier : displayItems) {
                    output.accept(itemSupplier.get());
                }
                if (dynamicItems != null) {
                    dynamicItems.accept(output);
                }
            })
            .build());
    }

    @SuppressWarnings("unchecked")
    private static Supplier<ItemLike> sup(Supplier<? extends ItemLike> s) { return (Supplier<ItemLike>) s; }
    private static Supplier<ItemLike> sup(ItemLike item) { return () -> item; }
}
